jury_task:
  description: >
    Evaluate the final arguments presented by both teams on the topic: {topic}.
    Use provided criteria to assess each team and declare the winner.
  expected_output: >
    A detailed evaluation including scores and a verdict on the winning team, with quotes from both teams' arguments.
  agent: jury

# Team 1 Tasks

team1_research_task:
  description: >
    Conduct thorough research on the topic: {topic}.
    Gather up-to-date, relevant information for Team 1’s argument.
  expected_output: >
    A concise list of 10 bullet points containing the most relevant information related to {topic}.
  agent: team1_researcher

team1_antithesis_task:
  description: >
    Generate challenging questions, arguments, or counterarguments in response to the opposing team’s stance.
    Use insights from both Team 1’s and the opposing team’s arguments.
  expected_output: >
    A well-structured antithesis with 5-7 strong arguments or counterpoints against the opposing team’s position.
  agent: team1_antithesis_generator

team1_final_text_task:
  description: >
    Summarize Team 1's position by crafting a compelling closing statement or summary
    that highlights their main points and refutes the opposing arguments.
  expected_output: >
    A clear, persuasive closing statement or summary that represents Team 1’s overall stance on {topic}.
  agent: team1_final_text_generator

# Team 2 Tasks

team2_research_task:
  description: >
    Conduct thorough research on the topic: {topic}.
    Gather up-to-date, relevant information for Team 2’s argument.
  expected_output: >
    A concise list of 10 bullet points containing the most relevant information related to {topic}.
  agent: team2_researcher

team2_antithesis_task:
  description: >
    Generate challenging questions, arguments, or counterarguments in response to the opposing team’s stance.
    Use insights from both Team 2’s and the opposing team’s arguments.
  expected_output: >
    A well-structured antithesis with 5-7 strong arguments or counterpoints against the opposing team’s position.
  agent: team2_antithesis_generator

team2_final_text_task:
  description: >
    Summarize Team 2's position by crafting a compelling closing statement or summary
    that highlights their main points and refutes the opposing arguments.
  expected_output: >
    A clear, persuasive closing statement or summary that represents Team 2’s overall stance on {topic}.
  agent: team2_final_text_generator
