
supervisor_task:
  description: >
    Act as the supervisor for the current team in the debate. 
    Decide the next action by selecting the appropriate agent (Researcher, Antithesis Generator, or Final Text Generator)
    based on the debate stage and arguments presented so far.
  expected_output: >
    The next agent's role (e.g., Researcher, Antithesis Generator, Speech Generator) or 'FINISH' when the team has completed its response for this stage.
  agent: team_supervisor

research_task:
  description: >
    Conduct thorough research on the topic: {topic}.
    Gather up-to-date, relevant information for the team’s argument.
  expected_output: >
    A concise list of 10 bullet points containing the most relevant information related to {topic}.
  agent: researcher

antithesis_task:
  description: >
    Generate challenging questions, arguments, or counterarguments in response to the opposing team’s stance.
    Use insights from both the team’s and the opposing team’s arguments.
  expected_output: >
    A well-structured antithesis with 5-7 strong arguments or counterpoints against the opposing team’s position.
  agent: antithesis_generator

final_text_generator_task:
  description: >
    Summarize Team {team_name}'s position by crafting a compelling closing statement or summary
    that highlights their main points and refutes the opposing arguments.
  expected_output: >
    A clear, persuasive closing statement or summary that represents the team’s overall stance on {topic}.
  agent: final_text_generator